services:
  agent:
    container_name: runafk-agent
    image: emreboga/runafk-agent:latest
    build:
      context: .
      dockerfile: packages/agent/Dockerfile
    env_file:
      - packages/agent/.env
    restart: unless-stopped
