import { Octokit } from '@octokit/rest';

const APPROVED_PLAN_MARKER = '<!-- runafk-approved-plan -->';

function client(): Octokit {
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

function parseRepo(): { owner: string; repo: string } {
  const [owner, repo] = (process.env.AGENT_REPO ?? '').split('/');
  if (!owner || !repo) throw new Error('AGENT_REPO must be in owner/repo format');
  return { owner, repo };
}

export async function listAssignedIssues(): Promise<string> {
  const octokit = client();
  const { owner, repo } = parseRepo();

  const { data } = await octokit.issues.listForRepo({
    owner,
    repo,
    state: 'open',
    assignee: (await octokit.users.getAuthenticated()).data.login,
    per_page: 20,
    sort: 'updated',
    direction: 'desc',
  });

  if (data.length === 0) return 'No open issues assigned to you.';

  return data
    .map((i) => `#${i.number}: ${i.title}`)
    .join('\n');
}

export async function getIssue(issueNumber: number): Promise<{ title: string; body: string }> {
  const { owner, repo } = parseRepo();
  const { data } = await client().issues.get({ owner, repo, issue_number: issueNumber });
  return { title: data.title, body: data.body ?? '' };
}

export async function getApprovedPlan(issueNumber: number): Promise<string | null> {
  const { owner, repo } = parseRepo();
  const { data } = await client().issues.listComments({ owner, repo, issue_number: issueNumber });
  const planComment = data.find((c) => c.body?.includes(APPROVED_PLAN_MARKER));
  if (!planComment?.body) return null;
  return planComment.body.replace(APPROVED_PLAN_MARKER, '').trim();
}

export async function postPlanComment(issueNumber: number, planText: string): Promise<void> {
  const { owner, repo } = parseRepo();
  await client().issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body: `${APPROVED_PLAN_MARKER}\n\n**RunAFK Approved Plan**\n\n${planText}`,
  });
}

export async function getAuthenticatedUser(): Promise<string> {
  const { data } = await client().users.getAuthenticated();
  return data.login;
}

export async function getAuthenticatedEmail(): Promise<string> {
  const { data } = await client().users.getAuthenticated();
  // GitHub may not expose email publicly; fall back to noreply address
  return data.email ?? `${data.login}@users.noreply.github.com`;
}

export async function createPullRequest(
  issueNumber: number,
  branch: string,
  title: string,
): Promise<string> {
  const { owner, repo } = parseRepo();
  const { data: repoData } = await client().repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  const { data } = await client().pulls.create({
    owner,
    repo,
    head: branch,
    base: defaultBranch,
    title,
    body: `Closes #${issueNumber}\n\n> This PR was generated by [RunAFK](https://github.com/runafk) using Claude Code.`,
  });
  return data.html_url;
}

export function cloneUrl(): string {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.AGENT_REPO;
  return `https://${token}@github.com/${repo}.git`;
}
