import { execSync, spawnSync } from 'child_process';
import fs from 'fs';
import os from 'os';
import path from 'path';
import type { CheckpointStatus } from '@runafk/shared';
import {
  listAssignedIssues,
  getIssue,
  getApprovedPlan,
  postPlanComment,
  createPullRequest,
  cloneUrl,
  getAuthenticatedUser,
  getAuthenticatedEmail,
} from './github';
import { runClaude, IMPLEMENT_TIMEOUT_MS } from './claude';

export type SendCheckpoint = (status: CheckpointStatus, text: string) => void;
export type SendResult = (text: string) => void;

// ─── /list ───────────────────────────────────────────────────────────────────

export async function handleList(sendResult: SendResult): Promise<void> {
  const list = await listAssignedIssues();
  sendResult(list);
}

// ─── /plan ───────────────────────────────────────────────────────────────────

export async function handlePlan(
  issueNumber: number,
  sendCheckpoint: SendCheckpoint,
  sendResult: SendResult,
): Promise<void> {
  sendCheckpoint('started', `Planning issue #${issueNumber}...`);

  const { title, body } = await getIssue(issueNumber);
  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'runafk-plan-'));

  try {
    execSync(`git clone --depth 1 ${cloneUrl()} .`, { cwd: workDir, stdio: 'pipe' });

    const prompt = [
      `You are a senior software engineer. Review this codebase and create a detailed implementation plan for the following GitHub issue.`,
      ``,
      `Issue #${issueNumber}: ${title}`,
      ``,
      body,
      ``,
      `Output ONLY the implementation plan — no code, just clear steps. Be specific about which files to change and why.`,
    ].join('\n');

    const planText = await runClaude(prompt, workDir);
    sendResult(planText);
  } finally {
    fs.rmSync(workDir, { recursive: true, force: true });
  }
}

// ─── /post_plan ──────────────────────────────────────────────────────────────

export async function handlePostPlan(
  issueNumber: number,
  planText: string,
  sendResult: SendResult,
): Promise<void> {
  await postPlanComment(issueNumber, planText);
  sendResult(`Plan posted to GitHub issue #${issueNumber}.`);
}

// ─── /implement ──────────────────────────────────────────────────────────────

export async function handleImplement(
  issueNumber: number,
  sendCheckpoint: SendCheckpoint,
  sendResult: SendResult,
): Promise<void> {
  sendCheckpoint('started', `Starting implementation of issue #${issueNumber}...`);

  // Fetch approved plan
  const planText = await getApprovedPlan(issueNumber);
  if (!planText) {
    sendResult(`No approved plan found for issue #${issueNumber}. Run \`/plan ${issueNumber}\` first.`);
    return;
  }

  const { title, body } = await getIssue(issueNumber);
  const branch = `runafk/issue-${issueNumber}`;
  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), `runafk-impl-`));

  try {
    // Clone and branch
    execSync(`git clone ${cloneUrl()} .`, { cwd: workDir, stdio: 'pipe' });
    execSync(`git checkout -b ${branch}`, { cwd: workDir, stdio: 'pipe' });

    // Configure git identity
    const ghUser = await getAuthenticatedUser();
    const ghEmail = await getAuthenticatedEmail();
    execSync(`git config user.name "${ghUser}"`, { cwd: workDir, stdio: 'pipe' });
    execSync(`git config user.email "${ghEmail}"`, { cwd: workDir, stdio: 'pipe' });

    // Run Claude Code
    const prompt = [
      `You are implementing a GitHub issue. You MUST write or modify actual files in this repository using your file tools.`,
      `Do NOT just explain what to do — make the changes now. Do not run tests or commit.`,
      `Only touch files directly relevant to this issue.`,
      ``,
      `Issue #${issueNumber}: ${title}`,
      ``,
      body,
      ``,
      `Approved implementation plan (follow this exactly):`,
      planText,
      ``,
      `Start implementing now. Write the code.`,
    ].join('\n');

    sendCheckpoint('started', 'Running Claude Code...');
    await runClaude(prompt, workDir, IMPLEMENT_TIMEOUT_MS);
    sendCheckpoint('code_completed', 'Code changes complete. Committing...');

    // Commit
    execSync('git add -A', { cwd: workDir, stdio: 'pipe' });

    // Check if there's anything to commit
    const diffResult = spawnSync('git', ['diff', '--staged', '--quiet'], { cwd: workDir });
    if (diffResult.status === 0) {
      throw new Error('Claude Code made no file changes. The implementation may have been incomplete.');
    }

    const commitMsg = `feat: implement issue #${issueNumber} — ${title}\n\nGenerated by RunAFK (Claude Code). Issue: #${issueNumber}`;
    const commitResult = spawnSync('git', ['commit', '-m', commitMsg], { cwd: workDir, encoding: 'utf-8' });
    if (commitResult.status !== 0) {
      throw new Error(`git commit failed:\n${(commitResult.stdout + commitResult.stderr).trim()}`);
    }

    // Run tests
    const testCmd = findTestCommand(workDir);
    if (testCmd) {
      sendCheckpoint('testing', `Running tests: \`${testCmd}\``);
      const result = spawnSync(testCmd, { cwd: workDir, shell: true, encoding: 'utf-8', timeout: 5 * 60 * 1000 });
      if (result.status !== 0) {
        const output = (result.stdout + result.stderr).slice(-2000);
        sendResult(`Tests failed:\n\`\`\`\n${output}\n\`\`\``);
        return;
      }
      sendCheckpoint('tests_passed', 'Tests passed.');
    } else {
      sendCheckpoint('testing', 'No test command found, skipping tests.');
    }

    // Push and open PR
    execSync(`git push origin ${branch}`, { cwd: workDir, stdio: 'pipe' });
    const prUrl = await createPullRequest(issueNumber, branch, `feat: implement issue #${issueNumber} — ${title}`);
    sendCheckpoint('pr_opened', `PR opened: ${prUrl}`);
    sendResult(prUrl);
  } finally {
    fs.rmSync(workDir, { recursive: true, force: true });
  }
}

// ─── Test command discovery ───────────────────────────────────────────────────

function findTestCommand(repoPath: string): string | null {
  const pkgPath = path.join(repoPath, 'package.json');
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    const scripts: Record<string, string> = pkg.scripts ?? {};
    // Prefer CI-friendly variants
    for (const name of ['test:ci', 'test:run', 'test']) {
      if (scripts[name]) return `npm run ${name}`;
    }
  }
  if (fs.existsSync(path.join(repoPath, 'pytest.ini')) || fs.existsSync(path.join(repoPath, 'pyproject.toml'))) {
    return 'pytest';
  }
  if (fs.existsSync(path.join(repoPath, 'Makefile'))) {
    const content = fs.readFileSync(path.join(repoPath, 'Makefile'), 'utf-8');
    if (/^test:/m.test(content)) return 'make test';
  }
  return null;
}
